# Anthropic HH Dataset Recipe: Gemma2 2B
# Optimized for Anthropic Helpful & Harmless dataset

# Import base configurations
includes:
  - ../configs/models/gemma2_2b.yaml
  - ../configs/datasets/anthropic_hh.yaml
  - ../configs/rewards/multi_objective.yaml

# Override dataset settings for Anthropic HH
dataset:
  preprocessing:
    max_length: 1536  # Anthropic HH dialogues are typically shorter
  
  batch_size: 6
  
  # Anthropic HH specific filtering
  filters:
    min_length: 20
    max_length: 1536
    remove_duplicates: true
    quality_threshold: 0.0

# Override reward settings - focus on helpfulness and harmlessness
reward:
  components:
    - name: "helpfulness"
      weight: 0.5
    - name: "harmlessness"
      weight: 0.5

# Training configuration
training:
  algorithm: "ppo"
  
  # Training hyperparameters
  num_epochs: 3
  steps_per_epoch: 1000
  learning_rate: 1e-5
  warmup_steps: 100
  
  # PPO specific
  ppo:
    num_ppo_epochs: 4
    mini_batch_size: 1
    gradient_accumulation_steps: 6
    ppo_clip_range: 0.2
    value_clip_range: 0.2
    kl_penalty: "kl"
    target_kl: 0.1
    gamma: 1.0
    lam: 0.95
    vf_coef: 0.1
    entropy_coef: 0.01
  
  # Optimization
  optimizer:
    type: "adamw"
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.01
  
  # Learning rate scheduler
  scheduler:
    type: "cosine"
    num_cycles: 0.5
    warmup_ratio: 0.1
  
  # Generation during training
  generation:
    max_new_tokens: 256
    temperature: 0.9
    top_p: 0.9
    do_sample: true
  
  # Logging
  logging:
    log_interval: 10
    eval_interval: 100
    save_interval: 500
    log_dir: "logs/anthropic_hh_gemma2"
    
  # Evaluation
  evaluation:
    num_samples: 150
    metrics: ["reward", "reward_helpfulness", "reward_harmlessness", "kl", "length", "perplexity"]
    
  # Checkpointing
  checkpointing:
    save_dir: "checkpoints/anthropic_hh_gemma2"
    save_total_limit: 3
    save_best: true
    metric_for_best_model: "reward"
    greater_is_better: true

# Hardware configuration
hardware:
  device: "cuda"
  mixed_precision: "bf16"
  gradient_checkpointing: true
  
  distributed:
    enabled: false
    backend: "nccl"
  
  memory:
    max_memory_per_gpu: null
    cpu_offload: false

# Experiment tracking
tracking:
  enabled: true
  backend: "wandb"
  project_name: "rlhf-training"
  run_name: "anthropic_hh_gemma2"
  tags: ["gemma2", "2b", "anthropic_hh", "ppo"]

# Misc
seed: 42
